### PR TITLE
feat(docs): navigate with left/right arrow keys

### PR DESCRIPTION
**Pull request by ydcjeff**
Enables docs navigation with left/right arrow keys. It can be useful for the ones who navigate with keyboard a lot.
More info : https://github.com/sphinx-doc/sphinx/pull/2064

### CODE REVIEW

**Comment by zhangguanheng66** [comment]
Can we have a preview of this change?

**Comment by zhangguanheng66** [comment]
cc @brianjo

**Comment by ydcjeff** [comment]
@zhangguanheng66 There is no artifacts uploaded in `build_doc` job as far as I found out.
But there is a preview from audio : https://174236-90321822-gh.circle-artifacts.com/0/docs/index.html

**Comment by zhangguanheng66** [comment]
I was wondering if we could avoid to collapse the navigation for "Package Reference".

**Comment by ydcjeff** [comment]
> I was wondering if we could avoid to collapse the navigation for "Package Reference".

That was caused by `pytorch_sphinx_theme`, I have sent a PR here https://github.com/pytorch/pytorch_sphinx_theme/pull/97

**Comment by zhangguanheng66** [comment]
> > I was wondering if we could avoid to collapse the navigation for "Package Reference".
> 
> That was caused by `pytorch_sphinx_theme`, I have sent a PR here [pytorch/pytorch_sphinx_theme#97](https://github.com/pytorch/pytorch_sphinx_theme/pull/97)

Thanks for the quick response. I will merge it once @brianjo approves it.

**Comment by zhangguanheng66** [comment]
I also have a request. Different from [vision](https://pytorch.org/vision/stable/index.html) and [audio](https://pytorch.org/audio/stable/index.html), the font of [text](https://pytorch.org/text/stable/index.html) is bold everywhere. Can we fix this for consistency?

**Comment by ydcjeff** [comment]
> I also have a request. Different from [vision](https://pytorch.org/vision/stable/index.html) and [audio](https://pytorch.org/audio/stable/index.html), the font of [text](https://pytorch.org/text/stable/index.html) is bold everywhere. Can we fix this for consistency?

I think that maybe cause of fonts torchtext using (Lato which has thick line width) while vision and audio is FreightSans which has thin line width. Both of 3 sites are using same font weight.

**Comment by zhangguanheng66** [comment]
> > I also have a request. Different from [vision](https://pytorch.org/vision/stable/index.html) and [audio](https://pytorch.org/audio/stable/index.html), the font of [text](https://pytorch.org/text/stable/index.html) is bold everywhere. Can we fix this for consistency?
> 
> I think that maybe cause of fonts torchtext using (Lato which has thick line width) while vision and audio is FreightSans which has thin line width. Both of 3 sites are using same font weight

Can we fix this? Or point me where to fix this. Thanks a lot.

**Comment by ydcjeff** [comment]
Sure you need to remove this line and `font-family` in [this file](https://github.com/pytorch/text/blob/master/docs/source/_static/css/pytorch_theme.css)

**Comment by zhangguanheng66** [comment]
> Sure you need to remove this line and `font-family` in [this file](https://github.com/pytorch/text/blob/master/docs/source/_static/css/pytorch_theme.css)

Not sure. It seems torchaudio also use Lato. See [here](https://github.com/pytorch/audio/blob/master/docs/source/_static/css/pytorch_theme.css#L1-L8).

**Comment by ydcjeff** [comment]
@zhangguanheng66 Updated the previous comment.
torchaudio doesn't have Lato font in https://github.com/pytorch/audio/blob/master/docs/source/conf.py

**Pull request closed without merging**
