### PR TITLE
Feature to ignore tokens

### PR DESCRIPTION
**Pull request by keitakurita**
Feature implementation for #354 
Simply added option to pass stop words to a field during initialization and have it remove words during preprocessing. API is based on the [CountTokenizer from scikit-learn](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html).
Stop words being an attribute of the field (not the vocab) seems natural when you consider the vocab as just a mapping from tokens to integers.

### CODE REVIEW

**Comment by mttk** [comment]
I'd just add a typecheck for `stop_words` to be a set (since people might pass a list as well) for speed. If it fails, cast it to list.
Either that or add that the stopwords have to be a set in the function doc.

**Comment by keitakurita** [comment]
Updated!

**Comment by mttk** [comment]
Great, thanks!

**Comment by manuelsh** [comment]
That's amazing! Thanks a lot!

**Pull request merged**
