### PR TITLE
[Bug Fixing][BC Breaking] Unify tar and zip handling with extract_archive

### PR DESCRIPTION
**Pull request by anmolsjoshi**
Corrected behavior described in this [PR](https://github.com/pytorch/text/pull/688#issuecomment-582543743) 

Before this PR:
```python
import os
from torchtext.utils import extract_archive, donwload_from_url

os.mkdir('.data')
download_from_url('https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip')
# '.data/wikitext-2-v1.zip'

extract_archive('.data/wikitext-2-v1.zip')
# ['wikitext-2/', 'wikitext-2/wiki.test.tokens', 'wikitext-2/wiki.valid.tokens', 'wikitext-2/wiki.train.tokens']
```

After this PR
```python
import os
from torchtext.utils import extract_archive, donwload_from_url

os.mkdir('.data')

download_from_url('https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip')
# '.data/wikitext-2-v1.zip'

extract_archive('.data/wikitext-2-v1.zip')
# ['.data/wikitext-2/wiki.test.tokens', '.data/wikitext-2/wiki.valid.tokens', '.data/wikitext-2/wiki.train.tokens']
```

**NOTE**: This PR is BC Breaking, if you are using this function to build custom datasets, there is no need to write code to join the root and extracted filenames. The outputted filenames have the root folder prepended to the extracted filenames.

### CODE REVIEW

**Comment by anmolsjoshi** [comment]
@zhangguanheng66 I updated the title and description of this PR

**Comment by anmolsjoshi** [comment]
I suspect the reason Github is oddly displaying tests/test_utils.py because of CRLF/LF. Although it does highlight what changed

**Comment by anmolsjoshi** [comment]
TODO: will be adding tests for overwrite option

**Comment by zhangguanheng66** [comment]
@cpuhrsch LGTM. I could run a smoke test to make sure the datasets work properly.

**Comment by cpuhrsch** [comment]
Let's sit on this a little bit to make sure it doesn't break a lot of stuff. @zhangguanheng66 - I think it's worth running more tests on your end.

**Comment by zhangguanheng66** [comment]
I have ran the smoke test for the release on the new branch and major datasets seem fine. The only difference, I notice, is that the directory path (e.g. 'wikitext-2/') is not included in the outputs of `extract_archive` function. This is different from the behaviors of the master branch.

**Comment by anmolsjoshi** [comment]
> I notice, is that the directory path (e.g. 'wikitext-2/') is not included in the outputs of extract_archive function. This is different from the behaviors of the master branch.

@zhangguanheng66 I can update the code so wikitext-2/ is returned. I personally think that only filenames should be returned from this function

**Comment by zhangguanheng66** [comment]
Did some offline research about the history of archive function. Long time ago (back to 2017), the download/archive functions were handled within `torchtext.dataset`. Then, `extract_archive` function was introduced with the support of tar file only. In October 2019, `extract_archive` function was extended to support zip file. But unfortunately, the `extract_archive` function has slightly different behaviors between tar and zip files (a.k.a. the root folder prepended to the path described by this PR). It's a bug fix and, IMP, the zip file should follow the behavior of the tar file. Thanks @anmolsjoshi for fixing it.

**Comment by zhangguanheng66** [comment]
And please address the fix in the unit test.

**Comment by zhangguanheng66** [comment]
@cpuhrsch there are two unit tests for `tar` and `zip`, respectively. In the tests, the extracted files have the paths with joint root and file path. see [here](https://github.com/pytorch/text/pull/692/commits/a4cdc72e0d9f157f423eb2bb2db611970aca3f26)

**Comment by anmolsjoshi** [comment]
@cpuhrsch following up about this PR

**Comment by zhangguanheng66** [comment]
Fix a bug introduced by https://github.com/pytorch/text/pull/602 where `extract_archive` func shows different behaviors for tar and zip files.

**Pull request merged**
