### PR TITLE
Fixed on_disk_cache issues

### PR DESCRIPTION
**Pull request by VitalyFedyunin**
Fixed issues with cache locks and cache files overwrites. Required to be compatible with https://github.com/pytorch/data/pull/810

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #1942

### CODE REVIEW

**Comment by Nayef211** [comment]
@VitalyFedyunin looks like all `TestCNNDM` is failing on all platforms. Will stamp once those are fixed!

**Comment by VitalyFedyunin** [comment]
Looks like tests havn't picked up recent torchdata changes, lets wait a bit and restart them.

**Comment by joecummings** [comment]
> Looks like tests havn't picked up recent torchdata changes, lets wait a bit and restart them.

These tests are now failing for every new PR. Which specific change is breaking this? @VitalyFedyunin

**Comment by VitalyFedyunin** [comment]
That PR https://github.com/pytorch/data/pull/810 introduced BC breaking change on cache api (as well as major stability fix). 
This PR is fixing all failed tests.

**Comment by VitalyFedyunin** [comment]
Not sure why 3.8 is failing. Something related to xml decoding.

**Comment by joecummings** [comment]
> Not sure why 3.8 is failing. Something related to xml decoding.

I think this is a transient error with that particular dataset. I'll approve but @Nayef211  can you confirm?

**Review by joecummings — APPROVED** [review]
lgtm

**Review by Nayef211 — APPROVED** [review]

**Comment by ejguan** [comment]
@Nayef211 @abhinavarora  Can we cherry pick this PR to the release?
We plan to cherry pick the one from torchdata https://github.com/pytorch/data/pull/810. And, since this is the PR fixing a bug https://github.com/pytorch/text/issues/1903

**Pull request merged**
