### PR TITLE
update documentation to reflect IMDB output

### PR DESCRIPTION
**Pull request by acxz**
When attempting to use the IMDB api, I got results that were different from what the docs suggested. This PR attempts to update the docs with the correct output of the IMDB api.

### CODE REVIEW

**Comment by Nayef211** [comment]
@acxz I think this might have been an oversight when the dataset was implemented. To be consistent with our other text classification dataset, we do want to return labels as integers. If you want to take this on, it would be as simple as adding a  `MAP_LABELS` similar to how we do it in the QNLI dataset.
https://github.com/pytorch/text/blob/fd49d42c6c90fc4b556b63227f3509292bbdba11/torchtext/datasets/qnli.py#L40

**Comment by acxz** [comment]
Ah I see, I'll take a stab at this in the upcoming weekend. Thanks for the implementation pointers.

**Comment by Nayef211** [comment]
@acxz lmk if you still plan on taking this on, otherwise I'm happy to submit a PR for it this week 😄

**Comment by acxz** [comment]
Yeah, actually if you could take it on that would be great. Ended up traveling this weekend and this week is looking a bit busy. Thanks for that!

**Comment by joecummings** [comment]
Closed in favor of #1914

**Pull request closed without merging**
