### PR TITLE
Cuda 11.8 & 12 builds and Python 3.11

### PR DESCRIPTION
**Pull request by johnnynunez**
Changes:
Python base test: 3.10 (Release in march by Anaconda)
Future Python 3.11 support
Cuda 11.8 builds
Cuda 12.0 builds

### CODE REVIEW

**Comment by joecummings** [comment]
cc @atalman @osalpekar

**Comment by osalpekar** [comment]
Looks like these are adding 3.11 support for the unittest jobs, but the jobs are failing due to version conflicts since some dependencies are not available for 3.11 in conda. We should perhaps wait for this until the deps are available and unittest jobs are able to run green reliably so the red signal doesn't affect torchtext dev's workflow - @joecummings lmk what you think about this.

**Comment by johnnynunez** [comment]
> Looks like these are adding 3.11 support for the unittest jobs, but the jobs are failing due to version conflicts since some dependencies are not available for 3.11 in conda. We should perhaps wait for this until the deps are available and unittest jobs are able to run green reliably so the red signal doesn't affect torchtext dev's workflow - @joecummings lmk what you think about this.

it's similar problem with torchvision, but in theory anaconda will release the python binaries already in mid-March. So, I already prepare test...

**Comment by joecummings** [comment]
> > Looks like these are adding 3.11 support for the unittest jobs, but the jobs are failing due to version conflicts since some dependencies are not available for 3.11 in conda. We should perhaps wait for this until the deps are available and unittest jobs are able to run green reliably so the red signal doesn't affect torchtext dev's workflow - @joecummings lmk what you think about this.
> 
> it's similar problem with torchvision, but in theory anaconda will release the python binaries already in mid-March. So, I already prepare test...

Got it. Thanks for the addition! I agree w/ @osalpekar that we'll wait until mid-March to merge, but I appreciate you being so on top of things here.

**Comment by johnnynunez** [comment]
> > > Looks like these are adding 3.11 support for the unittest jobs, but the jobs are failing due to version conflicts since some dependencies are not available for 3.11 in conda. We should perhaps wait for this until the deps are available and unittest jobs are able to run green reliably so the red signal doesn't affect torchtext dev's workflow - @joecummings lmk what you think about this.
> > 
> > 
> > it's similar problem with torchvision, but in theory anaconda will release the python binaries already in mid-March. So, I already prepare test...
> 
> Got it. Thanks for the addition! I agree w/ @osalpekar that we'll wait until mid-March to merge, but I appreciate you being so on top of things here.

conda 3.11 binaries are avaible

**Comment by johnnynunez** [comment]
Python 3.11 support added via https://github.com/conda/conda/pull/12256, this will be included in the May release of conda 23.5.0

**Pull request closed without merging**
