### PR TITLE
Update integration-test.yml

### PR DESCRIPTION
**Pull request by joecummings**

### CODE REVIEW

**Review by Nayef211 — COMMENTED** [review]
Can we fix the linter errors? Also the integration test failures look relevant

**Comment by rshraga** [comment]
@joecummings I can commandeer this. You mentioned having some additional context?

**Comment by joecummings** [comment]
yep feel free to commandeer. I'll chat you the extra context @rshraga

**Comment by joecummings** [comment]
Closing in favor of #2051

**Pull request closed without merging**
