### PR TITLE
Add sacremoses / toktok tokenizers

### PR DESCRIPTION
**Pull request by mttk**
Updated as recommended in #306.

### CODE REVIEW

**Comment by keon** [comment]
I believe this change is necessary since moses is deleted in nltk becasue of license issues.
ref: https://github.com/nltk/nltk/issues/2000

**Comment by mttk** [comment]
@keon agreed, I haven't merged this since I was unable to figure out / fix the failing test. 

I checked again after you commented, and the cause is revtok & python 2.7. The same test was failing on master. Feel free to merge either this (or #361), and close the other.

**Comment by mttk** [comment]
@jekbradbury I feel that the breaking test has something to do with 14418da (jekbradbury/revtok#3). Please check it out when you manage.

I will merge a patch to (currently) ignore that test in python 2.x.

**Comment by mttk** [comment]
Closing in favor of #361

**Comment by keon** [comment]
@mttk Python2.7 bug is fixed in the new sacremoses version. 
https://github.com/alvations/sacremoses/issues/4

**Pull request closed without merging**
