### PR TITLE
prepare datasets for new encoding kwarg.

### PR DESCRIPTION
**Pull request by erip**
This may need to wait for appropriate nightlies to be published, but @ejguan suggested this feature will make it into pytorch 1.11 so that's a good sign.

### CODE REVIEW

**Comment by ejguan** [comment]
Note: The PR with the change of encoding has already been merged into release/1.11 branch.

**Comment by Nayef211** [comment]
> This may need to wait for appropriate nightlies to be published, but @ejguan suggested this feature will make it into pytorch 1.11 so that's a good sign.

I think we're using the latest `main` branch for torchdata for our unit tests so our tests should not be failing if the `encoding` kwarg is already present in the torchdata repo. 

Here are the code pointers to where we are installing torchdata
- [linux unittests](https://github.com/pytorch/text/blob/main/.circleci/unittest/linux/scripts/install.sh#L16-L17)
- [windows unittests](https://github.com/pytorch/text/blob/main/.circleci/unittest/windows/scripts/install.sh#L21-L22)

**Comment by erip** [comment]
The encoding kwarg is in pytorch proper, not torchdata.

**Comment by Nayef211** [comment]
> The encoding kwarg is in [pytorch proper](https://github.com/pytorch/pytorch/blob/78e481d07d3ec94d89badf3beff52ca75615a10e/torch/utils/data/datapipes/iter/fileopener.py), not torchdata.

Ahh understood, thanks for clarifying!

**Comment by Nayef211** [comment]
Btw can we fix the merge conflicts with some of the datasets?

**Comment by erip** [comment]
Oops -- yep!

**Comment by parmeet** [comment]
Great to see this PR @erip! Hopefully we should soon be in position to land these changes :)

**Comment by erip** [comment]
This is a good sign. Once nightlies with Windows (and OS X) are published, this should be gtg -- Linux nightlies have propagated and tests pass in those cases.

**Review by parmeet — APPROVED** [review]
Overall the changes LGTM! We can merge once after the windows tests are passing. Thanks.

**Comment by erip** [comment]
New windows and OS X nightlies landed, so this should hopefully pass and be good to go. 🎆

**Pull request merged**
