### PR TITLE
Batch first for BPTTIterator

### PR DESCRIPTION
**Pull request by vin-ivar**
Transposes the text and target tensors if the text field has `batch_first` set to True.

### CODE REVIEW

**Comment by mttk** [comment]
I'll need to bring the repo up to date with recent flake8 fixes before merging this, probably won't have time to do this until the weekend. Thanks for the fix.

**Comment by vin-ivar** [comment]
Sounds good, cheers. I have a couple of other fixes I wanted to submit, do you want me to wait for the flake8 stuff to be done?

**Comment by mttk** [comment]
Feel free to submit them now, the flake stuff will be merged into the pull requests when it's done.

**Comment by sidhantnagpal** [comment]
It would be nice to have this in, I also came across this bug.
@mttk when is the next release due?

**Comment by mttk** [comment]
@sidhantnagpal not yet sure for the next release date, this bug is now fixed in master however.

**Pull request merged**
