### PR TITLE
Some simple c++ refactoring

### PR DESCRIPTION
**Pull request by cyyever**
Fix some warnings from clang-tidy due to the lack of parameter reference and using emplace_back to improve performance.

### CODE REVIEW

**Comment by parmeet** [comment]
Thank you @cyyever for making the contribution. Could you please provide a short summary/description of the changes in the description box?

**Comment by parmeet** [comment]
@cyyever Changes looks good to me..Do you think it would be useful to use emplace_back [here](https://github.com/pytorch/text/blob/25e8d002522e6ee781ac6a79f99a5583e775ae0b/torchtext/csrc/vocab.cpp#L375-L392) as well?

**Comment by cyyever** [comment]
> @cyyever Changes looks good to me..Do you think it would be useful to use emplace_back [here](https://github.com/pytorch/text/blob/25e8d002522e6ee781ac6a79f99a5583e775ae0b/torchtext/csrc/vocab.cpp#L375-L392) as well?

I have added.

**Review by parmeet — APPROVED** [review]
Thank you @cyyever for your contributions in improving torchtext's C++ code-base :).

**Pull request merged**
