### PR TITLE
Update v0.7.0 release branch with master

### PR DESCRIPTION
**Pull request by zhangguanheng66**
Let's test those recent changes in master branch first. We probably can cut the branch by July 20, 2020.
cc @cpuhrsch @Nayef211

### CODE REVIEW

**Comment by seemethere** [comment]
Are unittests expected to fail here?

**Comment by zhangguanheng66** [comment]
> Are unittests expected to fail here?

Glove link was broken due to the upstream dependency. @Nayef211 should we disable the tests again?

**Comment by seemethere** [comment]
Yeah I'm not sure I'd be comfortable tagging a new version with failing tests.

**Comment by zhangguanheng66** [comment]
> Yeah I'm not sure I'd be comfortable tagging a new version with failing tests.

OK, let me send out a PR to disable those test.

**Comment by zhangguanheng66** [comment]
https://github.com/pytorch/text/pull/888

**Pull request merged**
