### PR TITLE
Add Google Analytics support

### PR DESCRIPTION
**Pull request by NicolasHug**
This PR adds GA support to torchtext. We just rely on the native support from the theme (pytorch/pytorch_sphinx_theme#110)

### CODE REVIEW

**Review by vincentqb — APPROVED** [review]
LGTM too

**Comment by NicolasHug** [comment]
If you don't mind let's wait for https://github.com/pytorch/text/pull/1288 to be merged before merging this, in order to make sure the script is properly embeded in the html pages ;)

**Comment by vincentqb** [comment]
> If you don't mind let's wait for #1288 to be merged before merging this, in order to make sure the script is properly embedded in the html pages ;)

Approved that PR too :)

**Comment by NicolasHug** [comment]
It went fine, see e.g. the source of https://97382-76210069-gh.circle-artifacts.com/0/docs/experimental_vectors.html

Thanks for the review, merging!

**Pull request merged**
