### PR TITLE
migrate YelpReviewPolarity to datapipes.

### PR DESCRIPTION
**Pull request by erip**
Migrates dataset in `torchtext/datasets/`

Reference Issue: #1494

### CODE REVIEW

**Comment by erip** [comment]
These failures are interesting. Am I understanding correctly that the cache is pulled down daily in CI? Maybe these errors are related to the cache not being pulled yet? They seem unrelated as tests pass locally.

**Comment by parmeet** [comment]
> These failures are interesting. Am I understanding correctly that the cache is pulled down daily in CI? Maybe these errors are related to the cache not being pulled yet? They seem unrelated as tests pass locally.

Yes, you got it right. The cache is generated on daily cadence and sometimes fails to populate fully leading to failure of all datasets tests. Test reliability (among others) is one of the reasons we want to move away from caching datasets to mocking based testing in this issue #1493. Can you confirm that the tests related to this dataset are passing locally? I don't mind merging it into main as I know these errors are not related to your PR.

**Comment by erip** [comment]
Seems OK. This is for the other branch, but the changes are effectively the same. 

Passing tests locally

**Comment by erip** [comment]
Just confirmed this is OK.

**Review by Nayef211 — APPROVED** [review]
LGTM

**Pull request merged**
