### PR TITLE
DOC: move documentation to versioned folders

### PR DESCRIPTION
**Pull request by mattip**
Copy pytorch/audio#992 to this repo.
ping @brianjo. This enhancement to the gh-pages branch
- moves the documents around to allow versioning
- adds an index.html to redirect to stable/index.html
- adds a README.md 

Todo in future PRS:
- add a version selector like on the pytorch site
- automate doc building on a merge (to the "master" directory)
- automate doc building on a tag (to a numbered directory) (see pytorch/audio#1006)
- rethink serving the `_static` content. After this PR, each directory uses its own `_static` subdirectory, i.e, `0.8/index.html` uses `0.8/_static` resources for stylesheets and javascript. It would be nice if the content were shared across versions, so that a styling update would be applied to the older versions automatically: `0.8/index.html` would use `/_static`.

It might be difficult to review this PR because of all the changed files. I added a README.md to try to explain how it should work.

### CODE REVIEW

**Review by zhangguanheng66 — APPROVED** [review]
LGTM. Thanks for the contribution. @brianjo could you take a final look?

**Comment by brianjo** [comment]
This looks good to me as well.

**Comment by zhangguanheng66** [comment]
@brianjo and @mattip https://pytorch.org/text is mistakenly linked to audio website. Any ideas? I might have to revert this PR.

**Comment by mattip** [comment]
Whoops I must have copied the index.html as-is. Either revert it and I will re-submit when I am at a computer or see if you can spot the ‘audio’ in the index.html.

Sent from my phone

**Comment by zhangguanheng66** [comment]
> Whoops I must have copied the index.html as-is. Either revert it and I will re-submit when I am at a computer or see if you can spot the ‘audio’ in the index.html.
> 
> Sent from my phone

It works fine now. Thanks for the quick response. Another question. Any plan to automate the doc as torchaudio?

**Comment by mattip** [comment]
Thanks, sorry for the mess. Yes, I hope to finish the automation  up soon and then copy it here.

**Pull request merged**
