### PR TITLE
Build and test py3.10

### PR DESCRIPTION
**Pull request by atalman**
Build and test for Python 3.10

### CODE REVIEW

**Comment by parmeet** [comment]
@atalman could please try rebasing on the main, the unit-test failures doesn't make sense. It is likely due to some conflicting changes in config.yml.

**Comment by atalman** [comment]
@parmeet can you please take a look at this unit test failure ?  unittest_windows_py3.8

**Comment by parmeet** [comment]
> @parmeet can you please take a look at this unit test failure ? unittest_windows_py3.8

Please ignore this test failure. It's some randomness that causing this test failure. In worst-case we will just disable it, but for now it shouldn't be a blocker.

**Review by parmeet — APPROVED** [review]
LGTM!

**Pull request merged**
