### PR TITLE
todo-decorator-remove-solved

### PR DESCRIPTION
**Pull request by arnavmehta7**
Removed the code as the issue is closed.

### CODE REVIEW

**Comment by Nayef211** [comment]
@arnavmehta7 thanks for creating this! Can you please fix the [linter issues](https://app.circleci.com/pipelines/github/pytorch/text/6752/workflows/6d68e250-d994-490d-bc96-f5fd360f4a81/jobs/233009) that show up on CI before we merge the PR?

**Comment by arnavmehta7** [comment]
@Nayef211  thanks, but I'm quite new to this. I'm unable to solve this linting issue, can you tell me exactly how can I solve this? I'd be grateful of your help.

**Comment by arnavmehta7** [comment]
@Nayef211  Thanks, Corrected Linting

**Comment by arnavmehta7** [comment]
How can I fix these MacOS build issues?

**Comment by Nayef211** [comment]
> How can I fix these MacOS build issues?

This was fixed by https://github.com/pytorch/text/pull/1889 and should be fixed in your PR once you rebase on the latest main branch.

**Comment by arnavmehta7** [comment]
> > How can I fix these MacOS build issues?
> 
> This was fixed by #1889 and should be fixed in your PR once you rebase on the latest main branch.

Would I need to sync again then do these changes again?

**Comment by arnavmehta7** [comment]
Still MacOS errors?

**Comment by Nayef211** [comment]
> Still MacOS errors? Can you point out my mistake, I'm extremely sorry if I have done something wrong
> 
> EDIT: Still 3 errors :(

@arnavmehta7 the current failures are not related to your changes and are caused by flaky tests. Thanks again for working on this, I will stamp and merge this since the changes LGTM.

**Comment by arnavmehta7** [comment]
@Nayef211 Thanks for guidance, I've done that already :D

**Comment by arnavmehta7** [comment]
@Nayef211  Hey, It is working.

**Pull request closed without merging**
