### PR TITLE
hide symbols when building 3pp code

### LINKED ISSUE #1464: Should hide the symbols from the third party
I am integrating KenLM in torchaudio and realized that KenLM uses double-conversion like torchtext does.

In torchaudio we are hiding the symbols of third party with `-fhidden` flag with compiling, but it turns out that torchtext does not do this. (and according to the conversation I had with @malfet about a year ago, PyTorch also hides the symbol of their own code, in addition to third party.)

Torchtext may want to do this in case client code imports the same package compiled differently.

## References:
- https://stackoverflow.com/a/22254251
- https://labjack.com/news/simple-cpp-symbol-visibility-demo

## Double conversion

```
nm torchtext/_torchtext.so| grep double_c | grep 'T __' | head -10
0000000000175a48 T __ZN17double_conversion13StrtodTrimmedENS_6VectorIKcEEi
000000000017175c T __ZN17double_conversion16PowersOfTenCache32GetCachedPowerForDecimalExponentEiPNS_5DiyFpEPi
00000000001716fc T __ZN17double_conversion16PowersOfTenCache36GetCachedPowerForBinaryExponentRangeEiiPNS_5DiyFpEPi
00000000001715bc T __ZN17double_conversion6Bignum11PlusCompareERKS0_S2_S2_
000000000016f7cc T __ZN17double_conversion6Bignum12AssignBignumERKS0_
000000000016f788 T __ZN17double_conversion6Bignum12AssignUInt16Et
000000000016f7a0 T __ZN17double_conversion6Bignum12AssignUInt64Ey
0000000000171188 T __ZN17double_conversion6Bignum13SubtractTimesERKS0_i
00000000001702e8 T __ZN17double_conversion6Bignum14SubtractBignumERKS0_
000000000016ff70 T __ZN17double_conversion6Bignum15AssignHexStringENS_6VectorIKcEE
```

## Sentencepiece

```
$ nm torchtext/_torchtext.so| grep sentencep | grep 'T __' | head -10
0000000000128718 T __ZN13sentencepiece10ModelProto12InternalSwapEPS0_
00000000001277fc T __ZN13sentencepiece10ModelProto14_InternalParseEPKcPN6google8protobuf8internal12ParseContextE
000000000012765c T __ZN13sentencepiece10ModelProto16default_instanceEv
0000000000128334 T __ZN13sentencepiece10ModelProto21CheckTypeAndMergeFromERKN6google8protobuf11MessageLiteE
00000000001276a0 T __ZN13sentencepiece10ModelProto5ClearEv
0000000000128620 T __ZN13sentencepiece10ModelProto8CopyFromERKS0_
0000000000127650 T __ZN13sentencepiece10ModelProto9ArenaDtorEPv
0000000000128338 T __ZN13sentencepiece10ModelProto9MergeFromERKS0_
0000000000127168 T __ZN13sentencepiece10ModelProto9_Internal12trainer_specEPKS0_
0000000000127178 T __ZN13sentencepiece10ModelProto9_Internal14self_test_dataEPKS0_
```

### PR DESCRIPTION
**Pull request by erip**
Fixes #1464

### CODE REVIEW

**Comment by erip** [comment]
Failures look unrelated -- I think this is ready for review.

**Comment by erip** [comment]
@mthrok would you like to give my branch a spin to see if you're happy with it?

**Comment by mthrok** [comment]
Hi @erip 

Thanks for working on this. Here are my observations.
1. I see that the `-fhidden` flag is passed to re2 and torchtext but not to double_conversion and sentencepiece.
    <details><summary>commands</summary>
    
    ```
    {
      "directory": "/Users/moto/Development/text/third_party/build/re2",
      "command": "/Library/Developer/CommandLineTools/usr/bin/c++  -I/Users/moto/Development/text/third_party/re2 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk -fvisibility=hidden -pthread -std=gnu++11 -o CMakeFiles/re2.dir/util/strutil.cc.o -c /Users/moto/Development/text/third_party/re2/util/strutil.cc",
      "file": "/Users/moto/Development/text/third_party/re2/util/strutil.cc"
    },
    {
      "directory": "/Users/moto/Development/text/third_party/build/double-conversion",
      "command": "/Library/Developer/CommandLineTools/usr/bin/c++  -I/Users/moto/Development/text/third_party/double-conversion -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk -o CMakeFiles/double-conversion.dir/double-conversion/bignum.cc.o -c /Users/moto/Development/text/third_party/double-conversion/double-conversion/bignum.cc",
      "file": "/Users/moto/Development/text/third_party/double-conversion/double-conversion/bignum.cc"
    },
    ```
    
    </details>

2. The symbols from re2 and torchtext are now hidden.

    <details><summary>before</summary>

    ```
    $ nm torchtext/_torchtext.so| grep re2 | grep 'T __' | head -10
    000000000016eff0 T __ZN3re210chartoruneEPiPKc
    000000000016f0e0 T __ZN3re210runetocharEPcPKi
    00000000001603bc T __ZN3re211SparseArrayIiE4lessERKNS1_10IndexValueES4_
    000000000016831c T __ZN3re212RegexpStatus4CopyERKS0_
    0000000000168074 T __ZN3re212RegexpStatus8CodeTextENS_16RegexpStatusCodeE
    000000000016f630 T __ZN3re212StringPrintfEPKcz
    0000000000158648 T __ZN3re213CycleFoldRuneEi
    000000000015e7f4 T __ZN3re214ByteMapBuilder4MarkEii
    000000000015ed4c T __ZN3re214ByteMapBuilder5BuildEPhPi
    000000000015e914 T __ZN3re214ByteMapBuilder5MergeEv
    
    $ nm torchtext/_torchtext.so| grep double_c | grep 'T __' | head -10
    0000000000175a48 T __ZN17double_conversion13StrtodTrimmedENS_6VectorIKcEEi
    000000000017175c T __ZN17double_conversion16PowersOfTenCache32GetCachedPowerForDecimalExponentEiPNS_5DiyFpEPi
    00000000001716fc T __ZN17double_conversion16PowersOfTenCache36GetCachedPowerForBinaryExponentRangeEiiPNS_5DiyFpEPi
    00000000001715bc T __ZN17double_conversion6Bignum11PlusCompareERKS0_S2_S2_
    000000000016f7cc T __ZN17double_conversion6Bignum12AssignBignumERKS0_
    000000000016f788 T __ZN17double_conversion6Bignum12AssignUInt16Et
    000000000016f7a0 T __ZN17double_conversion6Bignum12AssignUInt64Ey
    0000000000171188 T __ZN17double_conversion6Bignum13SubtractTimesERKS0_i
    00000000001702e8 T __ZN17double_conversion6Bignum14SubtractBignumERKS0_
    000000000016ff70 T __ZN17double_conversion6Bignum15AssignHexStringENS_6VectorIKcEE
    
    $ nm torchtext/_torchtext.so| grep sentencep | grep 'T __' | head -10
    0000000000128718 T __ZN13sentencepiece10ModelProto12InternalSwapEPS0_
    00000000001277fc T __ZN13sentencepiece10ModelProto14_InternalParseEPKcPN6google8protobuf8internal12ParseContextE
    000000000012765c T __ZN13sentencepiece10ModelProto16default_instanceEv
    0000000000128334 T __ZN13sentencepiece10ModelProto21CheckTypeAndMergeFromERKN6google8protobuf11MessageLiteE
    00000000001276a0 T __ZN13sentencepiece10ModelProto5ClearEv
    0000000000128620 T __ZN13sentencepiece10ModelProto8CopyFromERKS0_
    0000000000127650 T __ZN13sentencepiece10ModelProto9ArenaDtorEPv
    0000000000128338 T __ZN13sentencepiece10ModelProto9MergeFromERKS0_
    0000000000127168 T __ZN13sentencepiece10ModelProto9_Internal12trainer_specEPKS0_
    0000000000127178 T __ZN13sentencepiece10ModelProto9_Internal14self_test_dataEPKS0_
    
    $ nm torchtext/_torchtext.so| grep torchtext | grep 'T __' | head -10
    0000000000056ea4 T __ZN3c1014getTypePtrCopyINS_13intrusive_ptrIN9torchtext13SentencePieceENS_6detail34intrusive_target_default_null_typeIS3_EEEEEENSt3__110shared_ptrINS_4TypeEEEv
    00000000000516b0 T __ZN3c1014getTypePtrCopyINS_13intrusive_ptrIN9torchtext14RegexTokenizerENS_6detail34intrusive_target_default_null_typeIS3_EEEEEENSt3__110shared_ptrINS_4TypeEEEv
    000000000004b004 T __ZN3c1014getTypePtrCopyINS_13intrusive_ptrIN9torchtext5RegexENS_6detail34intrusive_target_default_null_typeIS3_EEEEEENSt3__110shared_ptrINS_4TypeEEEv
    000000000006a7d0 T __ZN3c1014getTypePtrCopyINS_13intrusive_ptrIN9torchtext5VocabENS_6detail34intrusive_target_default_null_typeIS3_EEEEEENSt3__110shared_ptrINS_4TypeEEEv
    0000000000062844 T __ZN3c1014getTypePtrCopyINS_13intrusive_ptrIN9torchtext7VectorsENS_6detail34intrusive_target_default_null_typeIS3_EEEEEENSt3__110shared_ptrINS_4TypeEEEv
    00000000000558d4 T __ZN3c1014getTypePtrCopyINS_14tagged_capsuleIN9torchtext13SentencePieceEEEEENSt3__110shared_ptrINS_4TypeEEEv
    000000000004ea3c T __ZN3c1014getTypePtrCopyINS_14tagged_capsuleIN9torchtext14RegexTokenizerEEEEENSt3__110shared_ptrINS_4TypeEEEv
    00000000000420ac T __ZN3c1014getTypePtrCopyINS_14tagged_capsuleIN9torchtext5RegexEEEEENSt3__110shared_ptrINS_4TypeEEEv
    0000000000069584 T __ZN3c1014getTypePtrCopyINS_14tagged_capsuleIN9torchtext5VocabEEEEENSt3__110shared_ptrINS_4TypeEEEv
    0000000000060c38 T __ZN3c1014getTypePtrCopyINS_14tagged_capsuleIN9torchtext7VectorsEEEEENSt3__110shared_ptrINS_4TypeEEEv
    ```
    </details>

    <details><summary>after</summary>

    ```
    $ nm torchtext/_torchtext.so| grep re2 | grep 'T __' | head -10
    
    $ nm torchtext/_torchtext.so| grep double_c | grep 'T __' | head -10
    0000000000175940 T __ZN17double_conversion13StrtodTrimmedENS_6VectorIKcEEi
    0000000000171654 T __ZN17double_conversion16PowersOfTenCache32GetCachedPowerForDecimalExponentEiPNS_5DiyFpEPi
    00000000001715f4 T __ZN17double_conversion16PowersOfTenCache36GetCachedPowerForBinaryExponentRangeEiiPNS_5DiyFpEPi
    00000000001714b4 T __ZN17double_conversion6Bignum11PlusCompareERKS0_S2_S2_
    000000000016f6c4 T __ZN17double_conversion6Bignum12AssignBignumERKS0_
    000000000016f680 T __ZN17double_conversion6Bignum12AssignUInt16Et
    000000000016f698 T __ZN17double_conversion6Bignum12AssignUInt64Ey
    0000000000171080 T __ZN17double_conversion6Bignum13SubtractTimesERKS0_i
    00000000001701e0 T __ZN17double_conversion6Bignum14SubtractBignumERKS0_
    
    $ nm torchtext/_torchtext.so| grep sentencep | grep 'T __' | head -10
    0000000000127f18 T __ZN13sentencepiece10ModelProto12InternalSwapEPS0_
    0000000000126ffc T __ZN13sentencepiece10ModelProto14_InternalParseEPKcPN6google8protobuf8internal12ParseContextE
    0000000000126e5c T __ZN13sentencepiece10ModelProto16default_instanceEv
    0000000000127b34 T __ZN13sentencepiece10ModelProto21CheckTypeAndMergeFromERKN6google8protobuf11MessageLiteE
    0000000000126ea0 T __ZN13sentencepiece10ModelProto5ClearEv
    0000000000127e20 T __ZN13sentencepiece10ModelProto8CopyFromERKS0_
    0000000000126e50 T __ZN13sentencepiece10ModelProto9ArenaDtorEPv
    0000000000127b38 T __ZN13sentencepiece10ModelProto9MergeFromERKS0_
    0000000000126968 T __ZN13sentencepiece10ModelProto9_Internal12trainer_specEPKS0_
    0000000000126978 T __ZN13sentencepiece10ModelProto9_Internal14self_test_dataEPKS0_
    
    $ nm torchtext/_torchtext.so| grep re2 | grep 'T __' | head -10
    ```

    </details>
3. At the time sentencepiece is compiled I see that CMake issues a warning about the visibility
    <details>

    ```
    CMake Warning (dev) at src/CMakeLists.txt:272 (add_executable):
      Policy CMP0063 is not set: Honor visibility properties for all target
      types.  Run "cmake --help-policy CMP0063" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.

      Target "spm_export_vocab" of type "EXECUTABLE" has the following visibility
      properties set for CXX:

        CXX_VISIBILITY_PRESET

      For compatibility CMake is not honoring them for this target.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    ```

    </details>

For sentence piece, we need to figure out the policy around `CXX_VISIBILITY_PRESET`.
For double conversion, I quickly skimmed their CMakeLists.txt, but am not immediately clear why it's not honored.

**Comment by erip** [comment]
I think this looks a bit better, but unfortunately locally building on my Mac with `MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py clean install` is failing (with `/Users/erip/Code/text/torchtext/csrc/regex_tokenizer.h:9:25: error: unknown class name 'CustomClassHolder'; did you mean 'torch::jit::CustomClassHolder'?`) so I can't test it locally. I don't see the warning anymore, though.

**Comment by erip** [comment]
Figured out the mysterious compiler error: I somehow had an extremely old version of pytorch installed. Confirmed that this seems to do what's expected now:

```sh
(torchtext-dev) ➜  nm torchtext/_torchtext.so| grep re2 | grep 'T __' | head -10
(torchtext-dev) ➜  nm torchtext/_torchtext.so| grep double_c | grep 'T __' | head -10
(torchtext-dev) ➜  nm torchtext/_torchtext.so| grep sentencep | grep 'T __' | head -10
(torchtext-dev) ➜  nm torchtext/_torchtext.so| grep torchtext | grep 'T __' | head -10
```

I think this is ready for review.

**Comment by mthrok** [comment]
Hi @erip - I also confirm that symbols are now hidden. Thanks!

@parmeet This is ready and #1464 can be closed now.

**Comment by parmeet** [comment]
> Hi @erip - I also confirm that symbols are now hidden. Thanks!
> 
> @parmeet This is ready and #1464 can be closed now.

That's great! Thanks so much @erip for your contributions and @mthrok  for helping with the review process.

**Review by parmeet — APPROVED** [review]
LGTM!

**Pull request merged**
