### PR TITLE
fix non-UTF8 error

### PR DESCRIPTION
**Pull request by kobikun**
in python 2.7, there is exception for decoding word into utf8.
So I added the type checking and converting UTF8 codes.

### CODE REVIEW

**Comment by jekbradbury** [comment]
I think this is wrong on Py3? What you probably want is `six.bytestype`.

**Comment by kobikun** [comment]
I tried `six.bytestype`. but it is not work.
`six.string_types` is working on py2 and py3.

**Comment by jekbradbury** [comment]
Sorry, I meant `six.binary_type`. In Py3, the lines being read are `bytes` objects, so the `if` wouldn't be triggered for `str` or `six.string_types`.

**Comment by kobikun** [comment]
@jekbradbury  thanks~
I fix into `binary_type` and commited.

**Pull request merged**
