### PR TITLE
convert version text to link

### PR DESCRIPTION
**Pull request by mattip**
Convert the static version text to links in the 0.8 and 0.8.1 documentation

@brianjo

### CODE REVIEW

**Review by zhangguanheng66 — COMMENTED** [review]
Does this mean that we need to manually change this in the future?

**Comment by mattip** [comment]
No, going forward the documentation will be generated with this as part of the format template. 

Speaking of which, I see that v0.9.0-rc1 was tagged, but the tag commit did not trip the CI document upload. I think this is because the [job was canceled](https://app.circleci.com/pipelines/github/pytorch/text?branch=release%2F0.9)? @seemethere thoughts?

**Comment by mattip** [comment]
Do I need to do something more here?

**Comment by zhangguanheng66** [comment]
cc @brianjo Could you give a review?

**Review by brianjo — APPROVED** [review]

**Pull request merged**
