### PR TITLE
Add binary jobs for Windows

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes https://github.com/pytorch/text/issues/703.

### CODE REVIEW

**Comment by peterjc123** [comment]
Could you please take a look? @zhangguanheng66 @mthrok @cpuhrsch

**Comment by peterjc123** [comment]
Looks like the nightly jobs are not enabled in this repo. Any plan to do that?

**Comment by mthrok** [comment]
It's in our backlog but we don't have the bandwidth for it yet.
If you would like to contribute, that's highly appreciated :)

**Comment by peterjc123** [comment]
@mthrok I saw https://github.com/pytorch/audio/pull/306. What about replicating one in this repo?

**Comment by mthrok** [comment]
> @mthrok I saw pytorch/audio#306. What about replicating one in this repo?

Yes, that's what I have in my mind as well.

> BTW, I cannot contribute on this because I don't have access to the FB internal pages.

Oh, you are right. I will try to prioritize this. Thanks for signaling.

**Comment by mthrok** [comment]
@peterjc123 Another solution I had in my mind is cron schedule on Circle CI. https://circleci.com/docs/2.0/configuration-reference/#schedule
I have not looked into it yet, but with this, I feel we can run repeated jobs.

**Comment by peterjc123** [comment]
@mthrok You cannot use the cron syntax on CircleCI. See https://github.com/pytorch/pytorch/issues/26817.

**Comment by peterjc123** [comment]
@ezyang Do you have interest to bring the nightly support to this repo?

**Comment by mthrok** [comment]
> @mthrok You cannot use the cron syntax on CircleCI. See [pytorch/pytorch#26817](https://github.com/pytorch/pytorch/issues/26817).

Good to know. Thanks.

> @ezyang Do you have interest to bring the nightly support to this repo?

Could you consider this? I just tried to setup the Chronos job for torchtext by copying torchaudio's config but I do not have permission to setup the job.

**Comment by ezyang** [comment]
@mthrok I've added you to https://www.internalfb.com/intern/permission/group/2305955169720414/ so you should now have authorizations to create Chronos jobs as part of pytorch_oss_ci_oncall.

**Comment by mthrok** [comment]
Thanks!
moto 🛵

**Pull request merged**
