### PR TITLE
attempt to fix CPU-only bug.

### LINKED ISSUE #1539: Installing nightly TorchText with PyTorch forces CPU-only install
## 🐛 Bug
**Describe the bug**
When trying to install the nightly builds of PyTorch and TorchText with CUDA, the PyTorch install is coerced into a CPU-only one. 

Running `conda install pytorch torchtext cudatoolkit=11.3 -c pytorch-nightly` will try to install `pytorch==pytorch-nightly/linux-64::pytorch-1.11.0.dev20220126-py3.9_cpu_0`.

**To Reproduce**
Create a new conda environment, then try to install PyTorch and TorchText nightly builds with CUDA support.

```
conda create --name torchtext
conda activate torchtext
conda install pytorch torchtext cudatoolkit=11.3 -c pytorch-nightly
```

**Expected behavior**
Expected behavior should match the equivalent install process for e.g. TorchVision.
```
conda create --name torchvision
conda activate torchvision
conda install pytorch torchvision cudatoolkit=11.3 -c pytorch-nightly
```
This will try to install `pytorch==pytorch-nightly/linux-64::pytorch-1.11.0.dev20220126-py3.9_cuda11.3_cudnn8.2.0_0`, as expected (see also the below screenshots).

**Screenshots**

List of packages to be installed by `conda install pytorch torchtext -c pytorch-nightly`:

Screen Shot 2022-01-26 at 5 46 14 PM

List of packages to be installed by `conda install pytorch torchtext -c pytorch-nightly`:
Screen Shot 2022-01-26 at 5 47 17 PM

**Environment**

Results of environment collection script:

```
python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.29

Python version: 2.7.18 (default, Mar  8 2021, 13:02:45)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-81-generic-x86_64-with-Ubuntu-20.04-focal
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] # packages in environment at /private/home/ebs/miniconda/envs/torchtext:
```

### PR DESCRIPTION
**Pull request by erip**
Fixes #1539

I don't have a great way to test this, so maybe just good review until we can get GPU in CI? 😓

### CODE REVIEW

**Comment by erip** [comment]
I think there may be some things to address here regarding which channels are added depending on `CU_VERSION`...

**Comment by parmeet** [comment]
> Fixes #1539

Hi @erip. Thanks for proposing this PR.  Could you please share more details on if these changes are inspired from other domain libs? Unfortunately, I have limited understanding on this. 

@malfet, @seemethere  Wondering if these changes would indeed resolve the issue? I also see comment  here from @malfet 
 https://github.com/pytorch/text/pull/1520#issuecomment-1040920472, but I am not sure which changes exactly caused the issue.

**Comment by erip** [comment]
Yes, I'm trying to follow the packaging impls from vision and audio. These changes basically add support for newer CUDA toolkits and add these tools to the list of reqs as needed.

**Comment by parmeet** [comment]
> Yes, I'm trying to follow the packaging impls from vision and audio. These changes basically add support for newer CUDA toolkits and add these toolkits to the list of reqs as needed.

I see, I may be wrong here but since torchtext does not depend on GPU, so I am not sure if we necessarily need these dependencies. Moreover we don't have the issue #1539 for the stable release packages which does not have these packaging dependencies either. As per the comment here https://github.com/pytorch/text/pull/1520#issuecomment-1040920472 I am still trying to understand what changes have triggered the issue.  @mthrok  do you have some insights on issue #1539?

**Comment by erip** [comment]
I also may be wrong, but my understanding is that it adds them conditionally: if CU_VERSION is set, it will populate the dependencies correctly. If not, it will fall back to cpu. It's a bit unclear and I'd definitely love someone who has a better understanding to chime in. 

I also think there's some room for this to become a more standardized bit of infra among the various domain libs, but maybe we can address the immediate pain before the latent pain. 😄

**Comment by Nayef211** [comment]
@erip @parmeet should we go ahead and close this since the issue was fixed by reverting #1619?

**Comment by erip** [comment]
I'm ok with closing it. Do we have a sense of what broke?

**Comment by parmeet** [comment]
> I'm ok with closing it. Do we have a sense of what broke?

We fixed it just by reverting this PR https://github.com/pytorch/text/pull/1520. Presumably the introduction of Pytorch-mutex may have caused the issue. But there are few other changes in packaging so cannot really say for sure. Interestingly the version conflict didn't happen when the PR got reverted.

**Comment by parmeet** [comment]
> @erip @parmeet should we go ahead and close this since the issue was fixed by reverting #1619?

yupp I think it is safe to close it for now.

**Pull request closed without merging**
