### PR TITLE
Cleanup separate batch files on Windows

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by zhangguanheng66** [comment]
Please let us know if it's ready.

**Comment by peterjc123** [comment]
@zhangguanheng66 I think it's ready.

**Comment by zhangguanheng66** [comment]
@peterjc123 The Windows test on the master branch just fail.

**Comment by peterjc123** [comment]
@zhangguanheng66 Sorry, I made a typo here. Fix on the way.

**Pull request merged**
