### PR TITLE
fixing benchmark tests

### PR DESCRIPTION
**Pull request by parmeet**
We have modified our datasets and the way we pass splits and the way datasets are wrapped in decorator. In light of this some of the stuffs in benchmark suit need to be adapted.

### CODE REVIEW

**Review by zhangguanheng66 — APPROVED** [review]
Good catch! LGTM.

**Comment by parmeet** [comment]
> Good catch! LGTM.

In the same light, I think our examples folder is also potentially out-of-date with the latest changes.

**Comment by zhangguanheng66** [comment]
> > Good catch! LGTM.
> 
> In the same light, I think our examples folder is also potentially out-of-date with the latest changes.

We can either pick them up here, or I can send out a PR to fix that.

**Comment by parmeet** [comment]
> > > Good catch! LGTM.
> > 
> > 
> > In the same light, I think our examples folder is also potentially out-of-date with the latest changes.
> 
> We can either pick them up here, or I can send out a PR to fix that.

Sure, either way is fine I guess. I am not sure though if the diff become huge if there are potentially many files to fix? If so, we could go with separate PR as we find them.

**Pull request merged**
