### PR TITLE
[MRG] Set up tests, CI, and coverage

### PR DESCRIPTION
**Pull request by nelson-liu**
This PR sets up the beginnings of a test suite, runs it on CI with TravisCI, and logs coverage statistics with codecov.

To Do:
- [x] set up CI
- [x] set up coverage
- [x] set up lint
- [x] set up test suite
- [ ] fix project-wide lint
- [ ] write tests to reach an acceptable level of project-wide coverage

This isn't ready for review yet, but I thought it'd put it here in case you had feedback / wanted to push to it as well; I'll let you know when it is ready to be seriously looked at. 

You (or maybe @soumith / @apaszke , not sure what permissions you have on the repo) might have to twiddle some bits to get Travis and Codecov running on this repo. It should be fairly self explanatory, you just log into to the respective sites with your Github username and add the pytorch/text project to be tested / covered, and it should automatically start doing so. I've set them up on my fork already ([travis](https://travis-ci.org/nelson-liu/text/), [codecov](https://codecov.io/gh/nelson-liu/text))

Hoping to sit down and write some tests later this week / over the weekend.

### CODE REVIEW

**Comment by soumith** [comment]
OMG, CI and Tests <3 this is awesome. thanks a lot @nelson-liu

**Comment by jekbradbury** [comment]
Thanks Nelson!!
We have to merge this to actually start running travis/codecov -- should we do that now and put tests in another PR?

**Comment by nelson-liu** [comment]
Hmm, you should be able to just turn them on and have travis it build PR updates (in the settings). The next time I (or you, if you want to test it) push to this PR, then they should automatically run.

Alternatively, it might make sense to separate them as well --- just be aware that things will fail initially :) No strong opinions on either path.

**Comment by nelson-liu** [comment]
actually i think it makes more sense to merge this as is --- the PR could get pretty big if we shove all the tests in here, and ideally tests would be multiple PRs for individual classes.

**Comment by soumith** [comment]
travis is running https://travis-ci.org/pytorch/text

**Pull request merged**
