### PR TITLE
bug fix: snli data loader

### PR DESCRIPTION
**Pull request by sivareddyg**
The current SNLI dataset class fails for the test case test/snli.py.  Even the SNLI example in [examples/snli](https://github.com/pytorch/examples/blob/master/snli/train.py#L22) fails. 
This should fix it.

### CODE REVIEW

**Comment by jekbradbury** [comment]
Accidentally pushed to master a few minutes ago -- can you remove the last two commits?

**Comment by jekbradbury** [comment]
Also make sure to break line 40 in `snli.py` to satisfy the linter.

**Comment by sivareddyg** [comment]
@jekbradbury thanks! I was planning to do this today but since you already did, is there something else I have to do for this PR?

**Comment by sivareddyg** [comment]
@jekbradbury all checks passed :)

**Pull request merged**
