### PR TITLE
Optimize vocab from file construction 

### PR DESCRIPTION
**Pull request by Nayef211**
## Description
- Updated vocab from file construction to use counters instead of lists to reduce memory footprint
- Updated final tokens list to be sorted primarily by frequency and secondarily by lexicographic order

## Benchmarks
image

### CODE REVIEW

**Review by zhangguanheng66 — COMMENTED** [review]
LGTM. Just make sure that it works with the latest `basic_english_normalize`, which now accepts a list of strings, not a single string.

**Comment by Nayef211** [comment]
> LGTM. Just make sure that it works with the latest `basic_english_normalize`, which now accepts a list of strings, not a single string.

Will do that in a follow up PR. I'm keeping this PR to the optimizations when using counters.

**Review by zhangguanheng66 — APPROVED** [review]
LGTM. Let's wait for the CI tests.

**Comment by zhangguanheng66** [comment]
Eli just update the master branch to fix the windows unittest.

**Pull request merged**
