### PR TITLE
DOCS: remove 'git pull'

### PR DESCRIPTION
**Pull request by mattip**
continuation of gh-1105

Remove git pull, which was meant to solve a possible race condition (if between the time the CI run clones the repo, builds the project, builds the docs, and check out the gh-pages branch someone else has pushed a change to the branch), but does not work.

Please trigger a nightly build after merging this to test it out.

### CODE REVIEW

**Review by zhangguanheng66 — APPROVED** [review]
Let's merge it after the CI tests are OK

**Comment by mthrok** [comment]
Triggered nightly build

**Comment by mattip** [comment]
... and it failed. The gh-pages branch does need to be pulled before pushing.
```
To https://github.com/pytorch/audio.git
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/pytorch/audio.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I will try again in another PR, sorry.

**Comment by mattip** [comment]
Note there is no harm in the current state, since the doc push fails it should not break anything.

**Pull request merged**
