### PR TITLE
Add regex to "install_requires"

### PR DESCRIPTION
**Pull request by seemethere**
Fixes https://github.com/pytorch/text/issues/1951

### CODE REVIEW

**Review by osalpekar — APPROVED** [review]
Thanks! I'm wondering how this escaped smoke tests?

**Review by malfet — APPROVED** [review]
LGTM, but can we please get an ack from torchtext team that it is indeed the case. Also, why isn't there a torchdata dependency?

**Comment by joecummings** [comment]
The dependency on regex is relatively recent, but yes I'm also confused as to how this escaped smoke tests. Looking into this now. 

Also, it looks like you might need to add this here, as well: https://github.com/pytorch/text/blob/5eb33ce1f7447df5069b6cfb55b8177c9bbaff08/.circleci/unittest/windows/scripts/environment.yml#L8

CC @Nayef211 for question about Torchdata.

**Comment by seemethere** [comment]
> The dependency on regex is relatively recent, but yes I'm also confused as to how this escaped smoke tests. Looking into this now.
> 
> Also, it looks like you might need to add `regex` as a dependency here, as well:
> 
> https://github.com/pytorch/text/blob/5eb33ce1f7447df5069b6cfb55b8177c9bbaff08/.circleci/unittest/windows/scripts/environment.yml#L8
> 
> CC @Nayef211 for question about Torchdata.

I'm pretty sure regex gets installed as a transitive dependency for the unittest workflows which might explain the discrepancy. Also the binary builds don't run smoke tests (like importing torchtext) so it's understandable how this wasn't caught.

**Comment by seemethere** [comment]
As well, why do we even need this dependency in the first place? Is the built-in `re` module not good enough for the usecase of `findall`?

**Comment by Nayef211** [comment]
> As well, why do we even need this dependency in the first place? Is the built-in `re` module not good enough for the usecase of `findall`?
> 
> cc @rshraga

I'm not 100% sure why we didn't use `re` but you can find some relevant discussions around adding using regex in the [internal diff thread ](https://www.internalfb.com/diff/D40186470?dst_version_fbid=5257229001071858&transaction_fbid=476429154443011). IIUC this is a temporary addition and will be removed as soon as @rshraga migrates the regex pattern matching logic to a C++ operator.

> Also, why isn't there a torchdata dependency?

@malfet see https://github.com/pytorch/text/issues/1702 where we tagged you guys in asking what the process would be to make torchdata a required dep. I believe there was also an [internal chat thread](https://fb.workplace.com/chat/t/5361854030576540) about this but I'm not sure there was a resolution.

**Comment by seemethere** [comment]
> > As well, why do we even need this dependency in the first place? Is the built-in `re` module not good enough for the usecase of `findall`?
> > cc @rshraga
> 
> I'm not 100% sure why we didn't use `re` but you can find some relevant discussions around adding using regex in the [internal diff thread ](https://www.internalfb.com/diff/D40186470?dst_version_fbid=5257229001071858&transaction_fbid=476429154443011). IIUC this is a temporary addition and will be removed as soon as @rshraga migrates the regex pattern matching logic to a C++ operator.
> 
> > Also, why isn't there a torchdata dependency?
> 
> @malfet see #1702 where we tagged you guys in asking what the process would be to make torchdata a required dep. I believe there was also an [internal chat thread](https://fb.workplace.com/chat/t/5361854030576540) about this but I'm not sure there was a resolution.

Actually switching it to `re` provides no negative results so I'm just going to submit a new PR to do that instead

**Comment by seemethere** [comment]
Closing in favor of https://github.com/pytorch/text/pull/1953

**Pull request closed without merging**
